apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: ray-cluster
  namespace: ray-system
spec:
  rayVersion: '2.9.0'  # Ray 版本
  headGroupSpec:
    serviceType: ClusterIP
    rayStartParams:
      dashboard-host: '0.0.0.0'
      num-cpus: '4'
      num-gpus: '1'
    template:
      spec:
        containers:
        - name: ray-head
          image: rayproject/ray:2.9.0-py39-cu118
          ports:
          - containerPort: 6379  # Redis port
          - containerPort: 8265  # Ray dashboard
          - containerPort: 10001 # Ray client
          resources:
            limits:
              cpu: "4"
              memory: "16Gi"
              nvidia.com/gpu: "1"
            requests:
              cpu: "2"
              memory: "8Gi"
              nvidia.com/gpu: "1"
          volumeMounts:
          - name: ray-shared
            mountPath: /tmp/ray
          - name: rdma-devices
            mountPath: /dev/infiniband
        volumes:
        - name: ray-shared
          emptyDir: {}
        - name: rdma-devices
          hostPath:
            path: /dev/infiniband
  workerGroupSpecs:
  - groupName: gpu-workers
    replicas: 2
    minReplicas: 1
    maxReplicas: 10
    rayStartParams:
      num-cpus: '8'
      num-gpus: '4'
    template:
      spec:
        containers:
        - name: ray-worker
          image: rayproject/ray:2.9.0-py39-cu118
          resources:
            limits:
              cpu: "8"
              memory: "32Gi"
              nvidia.com/gpu: "4"
              rdma/hca_shared_devices: "1"
            requests:
              cpu: "4"
              memory: "16Gi"
              nvidia.com/gpu: "4"
              rdma/hca_shared_devices: "1"
          volumeMounts:
          - name: ray-shared
            mountPath: /tmp/ray
          - name: rdma-devices
            mountPath: /dev/infiniband
          env:
          - name: NCCL_IB_ENABLE
            value: "1"
          - name: NCCL_IB_HCA
            value: "mlx5_0,mlx5_1,mlx5_2,mlx5_3"
          - name: NCCL_IB_GID_INDEX
            value: "3"
          - name: NCCL_IB_TC
            value: "106"
          - name: NCCL_DEBUG
            value: "INFO"
        volumes:
        - name: ray-shared
          emptyDir: {}
        - name: rdma-devices
          hostPath:
            path: /dev/infiniband

---
apiVersion: v1
kind: Service
metadata:
  name: ray-dashboard
  namespace: ray-system
spec:
  ports:
  - port: 8265
    targetPort: 8265
    protocol: TCP
    name: dashboard
  selector:
    ray.io/group: headgroup
  type: NodePort 